# Generated by Django 6.1.1 on 2026-09-29 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=2)),
                ('name', models.CharField(max_length=128)),
                ('key', models.CharField(help_text='Normalized lookup key, see normalization.place_key().', max_length=128)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('land_area_sq_mi', models.FloatField(default=0)),
                ('source', models.CharField(choices=[('place', 'Census place'), ('place_alias', 'Alternate name of a Census place'), ('county_subdivision', 'Census county subdivision (township/town)')], max_length=32)),
            ],
            options={
                'ordering': ['state', 'name'],
                'constraints': [models.UniqueConstraint(fields=('state', 'key'), name='unique_place_key_per_state')],
            },
        ),
    ]
