# Generated by Django 6.1.1 on 2026-09-29 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FuelStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis_id', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=128)),
                ('state', models.CharField(db_index=True, max_length=2)),
                ('rack_id', models.PositiveIntegerField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=4, help_text='Retail price in USD per gallon.', max_digits=8)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['state', 'city', 'name'],
                'indexes': [models.Index(fields=['latitude', 'longitude'], name='stations_fu_latitud_a20c3d_idx')],
            },
        ),
    ]
