# Generated by Django 6.1.1 on 2026-09-30 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelstation',
            name='location_precision',
            field=models.CharField(choices=[('city_centroid', "Centre of the station's city"), ('exact', 'Coordinates supplied by the price feed')], default='city_centroid', max_length=16),
        ),
    ]
